### ISSUE TITLE
Create a new release?

### ISSUE THREAD

**Issue by amuraru** [ulucinar/kubectl-edit-status#4]
Hi - it would be useful to get https://github.com/ulucinar/kubectl-edit-status/commit/37b654f4d3baa59a914fafe7e1ff45f98ead142e in a release. Thanks!

**Comment by ulucinar** [comment]
Hi @amuraru,
Thank you for your request. I have released v0.2.0 containing the fix you mentioned. And here is the krew-index PR that will hopefully publish v0.2.0 in krew-index repo:
https://github.com/kubernetes-sigs/krew-index/pull/1258

I will report back here if the krew-index PR gets merged.

**Comment by ulucinar** [comment]
Hi,
https://github.com/kubernetes-sigs/krew-index/pull/1258, which bumps edit-status version to v0.2.0, has been merged successfully.

**Comment by amuraru** [comment]
Big thanks!

**Comment by amuraru** [comment]
Awesome plugin by the way!

**Comment by ulucinar** [comment]
Thank you @amuraru, that's very kind of you.
