### ISSUE TITLE
Support KUBE_EDITOR environment variable with command line options

### ISSUE THREAD

**Issue by vsliouniaev** [ulucinar/kubectl-edit-status#7]
Using the envronment variable
```
KUBE_EDITOR="code -w"
```
results in `Error: exec: "code -w": executable file not found in $PATH`

**Comment by ulucinar** [comment]
Hi @vsliouniaev,
Thank you! I did not know that we can use `code` in this way with `edit-status`. With #14, I have verified the following now works:
```
KUBE_EDITOR="code -w" kubectl edit-status pods/example-pod
```
, after the edited file is saved and the editor tab is closed.
