### ISSUE TITLE
Support CRD shortNames

### ISSUE THREAD

**Issue by piepmatz** [ulucinar/kubectl-edit-status#9]
CRDs allow specifying a list of `shortNames`.

The `edit-status` plugin does not support those yet.

**Comment by ulucinar** [comment]
Thank you @piepmatz for the suggestion. #15 adds support for both automatic scope inference and usage of CRD short names in partial resource specifications. For example, it's now possible to run:
```
kubectl edit-status rg example
```
, where `rg` is a short name for `resourcegroup.azure.jet.crossplane.io`.
